version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/gitlab_insights
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gitlab_insights
  redis:
    image: redis:6


version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


services:
  # ... other services ...

  scheduled_analytics:
    build: .
    command: python scheduled_analytics.py
    volumes:
      - .:/app
    depends_on:
      - api


version: '3'

services:
  data_service:
    build: ./data_service
    ports:
      - "50051:50051"

  model_service:
    build: ./model_service
    ports:
      - "50052:50052"

  analytics_service:
    build: ./analytics_service
    ports:
      - "50053:50053"

  api_gateway:
    build: ./api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - data_service
      - model_service
      - analytics_service

  # Add other necessary services (e.g., database, Kafka, etc.)
